#!/bin/bash -v

version=1.0.1

R CMD BUILD Mega2R
R CMD check --as-cran "$@" Mega2R_$version.tar.gz

# devtools::document("Mega2R")
# devtools::install("Mega2R")
# devtools::build("Mega2R")
# devtools::check("Mega2R")
# devtools::build_vignettes("Mega2R")
# devtools::run_examples("Mega2R")
