#!/bin/bash

TEST=~/mega2/test
BLD=change_chrom/bed
FILES1="fam freq map pen phe vcf"
FILES2="fam freq map pen vcf"
nd=492

ds=mex
echo $ds $TEST/${ds}${nd}/$BLD/vcf/vcf.05.sfx
for sfx in $FILES2; do
    echo diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.05.$sfx
    diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.05.$sfx
done

ds=mec
echo $ds $TEST/${ds}${nd}/$BLD/vcf/vcf.05.sfx
for sfx in $FILES2; do
    echo diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.05.$sfx
    diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.05.$sfx
done

ds=mome
echo $ds $TEST/${ds}${nd}/$BLD/vcf/vcf.01.sfx
for sfx in $FILES2; do
    echo diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.01.$sfx
    diff -w $ds/$ds.$sfx $TEST/${ds}${nd}/$BLD/vcf/vcf.01.$sfx
done

ds=tst
echo $ds $TEST/Xxample/${ds}${nd}/$BLD/vcf/vcf.22.sfx
for sfx in $FILES2; do
    echo diff -w $ds/$ds.$sfx $TEST/Xxample/${ds}${nd}/$BLD/vcf/vcf.22.$sfx
    diff -w $ds/$ds.$sfx $TEST/Xxample/${ds}${nd}/$BLD/vcf/vcf.22.$sfx
done

ds=msat
echo $ds/vcf/vcf.16.sfx $TEST/${ds}${nd}/change_chrom/plink/vcf/vcf.16.sfx
for sfx in $FILES2; do
    echo diff -w $ds/vcf/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcf/vcf.16.$sfx
    diff -w $ds/vcf/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcf/vcf.16.$sfx
done
echo $ds/vcfmaj/vcf.16.sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmaj/vcf.16.sfx
for sfx in $FILES2; do
    echo diff -w $ds/vcfmaj/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmaj/vcf.16.$sfx
    diff -w $ds/vcfmaj/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmaj/vcf.16.$sfx
done
echo $ds/vcfmin/vcf.16.sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmin/vcf.16.sfx
for sfx in $FILES2; do
    echo diff -w $ds/vcfmin/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmin/vcf.16.$sfx
    diff -w $ds/vcfmin/vcf.16.$sfx $TEST/${ds}${nd}/change_chrom/plink/vcfmin/vcf.16.$sfx
done

ds=yj1
ds2=yj2
echo $ds / $ds2
for sfx in $FILES1; do
    echo diff -w yj/$ds.$sfx yj/$ds2.$sfx 
    diff -w yj/$ds.$sfx yj/$ds2.$sfx 
done

