# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getgenotypes_Ci <- function(locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg) {
    .Call('mega2_getgenotypes_Ci', PACKAGE = 'mega2', locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg)
}

getgenotypes_Ri <- function(locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg) {
    .Call('mega2_getgenotypes_Ri', PACKAGE = 'mega2', locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg)
}

