// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getgenotypes_Ci
Rcpp::Matrix<STRSXP> getgenotypes_Ci(NumericVector locus_arg, NumericVector hocus_arg, List genotype_arg, List allele_arg, List markerscheme_arg, NumericVector phenocnt_arg);
RcppExport SEXP mega2_getgenotypes_Ci(SEXP locus_argSEXP, SEXP hocus_argSEXP, SEXP genotype_argSEXP, SEXP allele_argSEXP, SEXP markerscheme_argSEXP, SEXP phenocnt_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type locus_arg(locus_argSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hocus_arg(hocus_argSEXP);
    Rcpp::traits::input_parameter< List >::type genotype_arg(genotype_argSEXP);
    Rcpp::traits::input_parameter< List >::type allele_arg(allele_argSEXP);
    Rcpp::traits::input_parameter< List >::type markerscheme_arg(markerscheme_argSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phenocnt_arg(phenocnt_argSEXP);
    rcpp_result_gen = Rcpp::wrap(getgenotypes_Ci(locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg));
    return rcpp_result_gen;
END_RCPP
}
// getgenotypes_Ri
Rcpp::Matrix<STRSXP> getgenotypes_Ri(NumericVector locus_arg, NumericVector hocus_arg, List genotype_arg, List allele_arg, List markerscheme_arg, NumericVector phenocnt_arg);
RcppExport SEXP mega2_getgenotypes_Ri(SEXP locus_argSEXP, SEXP hocus_argSEXP, SEXP genotype_argSEXP, SEXP allele_argSEXP, SEXP markerscheme_argSEXP, SEXP phenocnt_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type locus_arg(locus_argSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hocus_arg(hocus_argSEXP);
    Rcpp::traits::input_parameter< List >::type genotype_arg(genotype_argSEXP);
    Rcpp::traits::input_parameter< List >::type allele_arg(allele_argSEXP);
    Rcpp::traits::input_parameter< List >::type markerscheme_arg(markerscheme_argSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phenocnt_arg(phenocnt_argSEXP);
    rcpp_result_gen = Rcpp::wrap(getgenotypes_Ri(locus_arg, hocus_arg, genotype_arg, allele_arg, markerscheme_arg, phenocnt_arg));
    return rcpp_result_gen;
END_RCPP
}
